### ISSUE TITLE
UMAP from ENHANCE counts

### ISSUE THREAD

**Issue by romanhaa** [yanailab/enhance#2]
ENHANCE is so fantastically simply and fast that I had to try it immediately.

Since I'm using the Seurat for most of my analyses, I used it to see the impact of ENHANCE on cluster and dimensional reduction. After using ENHANCE, I find many more clusters and noticed some strange looking shapes in the UMAP. I'm not sure I understood the procedure you described in the supplementary methods, but could it be that normalizing, PCA transformation and scaling the data introduces too smoothing (or whatever you might call it) which leads to these shapes?

Here is the code and UMAP made with the raw counts:

```r
seurat_raw <- CreateSeuratObject(raw_sparse)
seurat_raw <- NormalizeData(seurat_raw)
seurat_raw <- FindVariableFeatures(seurat_raw)
seurat_raw <- ScaleData(seurat_raw)
seurat_raw <- RunPCA(seurat_raw)
seurat_raw <- FindNeighbors(seurat_raw)
seurat_raw <- FindClusters(seurat_raw)
seurat_raw <- RunUMAP(seurat_raw, dims = 1:30)
```

![UMAP_raw](https://user-images.githubusercontent.com/18103560/59037769-38acaa80-8872-11e9-921d-ce2dcc5ee169.png)

Here the code and UMAP after using ENHANCE:

```r
seurat_enhance <- CreateSeuratObject(enhance_sparse)
seurat_enhance <- NormalizeData(seurat_enhance)
seurat_enhance <- FindVariableFeatures(seurat_enhance)
seurat_enhance <- ScaleData(seurat_enhance)
seurat_enhance <- RunPCA(seurat_enhance)
seurat_enhance <- FindNeighbors(seurat_enhance)
seurat_enhance <- FindClusters(seurat_enhance)
seurat_enhance <- RunUMAP(seurat_enhance, dims = 1:30)
```

![UMAP_enhance](https://user-images.githubusercontent.com/18103560/59037779-3ea28b80-8872-11e9-9aaf-d2b7ae3daa4c.png)

I'm using R 3.5.2 and Seurat v3 but I don't think that matters a lot.

**Comment by Puriney** [comment]
You are comparing two different unsupervised clustering results. Could you color the first 11 clusters to the second result, or put the other way around, color the 21 clusters back to the first result?

**Comment by flo-compbio** [comment]
Hi Roman,

> ENHANCE is so fantastically simply and fast that I had to try it immediately.

Thank you for giving it a try!

> Since I'm using the Seurat for most of my analyses, I used it to see the impact of ENHANCE on cluster and dimensional reduction. After using ENHANCE, I find many more clusters and noticed some strange looking shapes in the UMAP. I'm not sure I understood the procedure you described in the supplementary methods, but could it be that normalizing, PCA transformation and scaling the data introduces too smoothing (or whatever you might call it) which leads to these shapes?

I agree that it's a natural idea to try and see what happens when you apply clustering or dimensionality reduction to the denoised data produced by ENHANCE. ("Shouldn't the results improve?") However, you have to keep two things in mind: First, ENHANCE gets rid of noise by projecting the (aggregated) data onto a few principal components. So we go from a very high dimensional space to representing the data using, say, 20 dimensions. This gets rid of noise very effectively, but it can also create artificial structure. So I think this explains the little "spikes" and "lines" that you see in the UMAP plot. Second, the existing clustering and visualization techniques for single-cell RNA-Seq were designed with the assumption that the data is very noisy, and this can create problems. For example, a lot of the steps that Seurat uses in its clustering workflow such as gene selection may not work as intended anymore after you get rid of the noise. Similarly, t-SNE and UMAP have their own ways of overcoming noise by defining local neighborhoods and making sure that neighboring cells remain in close proximity. So ironically, running specialized clustering or visualization algorithms on denoised data may actually give _worse_ results.

For now, I would therefore run clustering and visualization on the raw data, and then only use the denoised data to examine the expression pattern of individual genes. However, as we write in the paper, there are definitely ways to leverage ENHANCE for other machine learning tasks such as clustering and visualization, and we have something in the works that I hope you'll find useful. If you follow me on twitter (@flo_compbio) you'll hear about it as soon as it's published.

**Comment by romanhaa** [comment]
Hi Florian,

Thank you for the explanation and the clarification, that makes a lot of sense! I wasn't able to put it into words like this but you hit the nail on the head. Very excited to hear about those other tools you are developing!

Best,
Roman

**Comment by flo-compbio** [comment]
Hi Roman,

I've thought about your question a little bit more and I've done a bit more testing to come up with some more helpful ideas for how to treat cases like yours.

So first I would like to clarify what I wrote earlier regarding the artifacts that show up in your UMAP (and I think they are even more apparent in t-SNE). They don't simply result from the dimensionality reduction (otherwise you would see the same thing in the original UMAP), but from the fact that we perform a nearest-neighbor aggregation step, and that the neighbors are identified based on distances in a low-dimensional space. So the cells get projected onto principal components, and then the neighbors for each cell are identified. I think what happens is that sometimes cells get kind of "lined up" along a specific PC, and as a result, you sometimes see these linear patterns in the denoised data.

Regarding your specific dataset, it looks like denoising is pretty crucial, as it's quite difficult to see much structure in the original UMAP. But then the question is how should you go about clustering the data? So my simple answer to that would be: by going back to heatmaps and hierarchical clustering! That's probably the most widely used approach for bulk RNA-Seq data, but for single-cell data it doesn't work because the data generally is generally so noisy that the gene-gene or cell-cell correlations aren't very good. But after denoising, heatmaps work just fine and they allow you to cluster with much higher granularity and with a better visual reference than what you get from t-SNE or UMAP. You generally want to select a set of maybe 500-1,000 variable genes for your heatmap, and I'm happy to share with you my recommendation for how to select those. Maybe just send me an email (florian.compbio@gmail.com).

**Comment by romanhaa** [comment]
Wow, thanks for the greatly appreciated feedback! That actually makes a lot of sense. I had seen cells  line up in projections (t-SNE, UMAP) before when using other imputation tools which probably work in a similar way to ENHANCE and therefore created these structures.

Going back to "old school" heatmaps is definitely an interesting idea that I hadn't though of yet. I'll shoot you a message and would be happy to get your recommendations.
